name: flutter_firebase
description: A Flutter demo app to interact with various Firebase services
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.4.0
  cloud_functions: ^5.1.0
  dio: ^5.4.0
  firebase_analytics: ^11.3.0
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  firebase_storage: ^12.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.1.2  
  firebase_crashlytics: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
     - res/firebase_compendium_logo.png
     - res/github.png
     - res/medium.png
     - res/quickcoder.png